//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Class()
        {
            this.Class_Instructors = new HashSet<Class_Instructors>();
            this.ClassWaitLists = new HashSet<ClassWaitList>();
            this.ClassEnrollments = new HashSet<ClassEnrollment>();
            this.ClassAvailablePlacements = new HashSet<ClassAvailablePlacement>();
            this.EnrollmentComments = new HashSet<EnrollmentComment>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int ClassTypeId { get; set; }
        public int StudioRoomId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Duration { get; set; }
        public int MaxParticipants { get; set; }
        public int Participants { get; set; }
        public bool IsForMale { get; set; }
        public bool IsForFemale { get; set; }
        public Nullable<bool> IsFull { get; set; }
        public bool IsDeleted { get; set; }
        public int DailySlotId { get; set; }
        public int WaitingList { get; set; }
        public string ShortURL { get; set; }
        public double Rating { get; set; }
        public bool IsMultiRoom { get; set; }
        public Nullable<int> ClassTypeDetailsId { get; set; }
        public bool Published { get; set; }
        public int ExtraParticipants { get; set; }
        public int MaxExtraParticipants { get; set; }
        public int MinAge { get; set; }
        public int AgeGroup { get; set; }
        public bool UsePlacements { get; set; }
    
        public virtual ClassDailySlot ClassDailySlot { get; set; }
        public virtual ClassType ClassType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Class_Instructors> Class_Instructors { get; set; }
        public virtual StudioRoom StudioRoom { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassWaitList> ClassWaitLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassEnrollment> ClassEnrollments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassAvailablePlacement> ClassAvailablePlacements { get; set; }
        public virtual ClassTypeDetail ClassTypeDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnrollmentComment> EnrollmentComments { get; set; }
    }
}
