//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class_Instructors
    {
        public int Id { get; set; }
        public int ClassId { get; set; }
        public string InstructorId { get; set; }
        public bool Verified { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Class Class { get; set; }
    }
}
