//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassAvailablePlacement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClassAvailablePlacement()
        {
            this.ClassEnrollments = new HashSet<ClassEnrollment>();
        }
    
        public int Id { get; set; }
        public int ClassId { get; set; }
        public int StudioPlacementId { get; set; }
        public string StudioPlacementName { get; set; }
        public byte ClassPlacementNumber { get; set; }
        public bool IsInUse { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual StudioPlacement StudioPlacement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassEnrollment> ClassEnrollments { get; set; }
    }
}
