//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.BalanceChangeTypes = new HashSet<BalanceChangeType>();
            this.MSGTypes = new HashSet<MSGType>();
            this.SMSSettings = new HashSet<SMSSetting>();
            this.Studios = new HashSet<Studio>();
            this.Subscribers = new HashSet<Subscriber>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string ManagerName { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public System.DateTime StartDate { get; set; }
        public bool UseSMS { get; set; }
        public bool UseHosting { get; set; }
        public bool Active { get; set; }
        public bool IsDeleted { get; set; }
        public string CompanyCode { get; set; }
        public string WebSiteURL { get; set; }
        public string SiteName { get; set; }
        public string LogoURL { get; set; }
        public string CSSFileName { get; set; }
        public int CancellationThresholdMins { get; set; }
        public Nullable<int> SpacesLeftToShow { get; set; }
        public bool HealthTandCEnabled { get; set; }
        public bool ClassRatingEnabled { get; set; }
        public string GoogleAPIKey { get; set; }
        public Nullable<System.DateTime> HostingRenewDate { get; set; }
        public string StudioRoomName { get; set; }
        public bool UseClassNamefromType { get; set; }
        public bool WaitingListEnabled { get; set; }
        public int WaitingListSpaces { get; set; }
        public string TipsName { get; set; }
        public string CalanderMode { get; set; }
        public bool UseInstructors { get; set; }
        public bool UseExpenses { get; set; }
        public bool UseClassTypeDetails { get; set; }
        public int NumAdvncedEnrollments { get; set; }
        public bool ManageAfterRegister { get; set; }
        public bool AutoPublish { get; set; }
        public int LateRegistration { get; set; }
        public bool UsePlacements { get; set; }
        public bool UseAgeforGender { get; set; }
        public int PriorityWaitListDays { get; set; }
        public int AdultAge { get; set; }
        public int TeenAge { get; set; }
        public int LateCancelation { get; set; }
        public string LateCancelPenalty { get; set; }
        public bool RemoveMarked { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BalanceChangeType> BalanceChangeTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MSGType> MSGTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMSSetting> SMSSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Studio> Studios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subscriber> Subscribers { get; set; }
    }
}
