//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyExport
    {
        public int ClassEnrollmentId { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Address { get; set; }
        public int Gender { get; set; }
        public bool ReceiveSMS { get; set; }
        public int StudioId { get; set; }
        public string UserId { get; set; }
        public bool Active { get; set; }
        public bool Frozen { get; set; }
        public string SubscriptionName { get; set; }
        public System.DateTime Date { get; set; }
        public int SubscriptionId { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<System.DateTime> LastClassDate { get; set; }
        public string LastClass { get; set; }
        public Nullable<System.DateTime> NextClassDate { get; set; }
        public string NextClass { get; set; }
        public Nullable<int> DaysSinceLastClass { get; set; }
        public bool IsLateCancel { get; set; }
    }
}
