//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnrollmentComment
    {
        public int Id { get; set; }
        public int EnrollmentId { get; set; }
        public string UserId { get; set; }
        public int ClassId { get; set; }
        public string Comment { get; set; }
        public string UserCreated { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual Class Class { get; set; }
        public virtual ClassEnrollment ClassEnrollment { get; set; }
    }
}
