//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FrozenSubscription
    {
        public int Id { get; set; }
        public int SubscriptionId { get; set; }
        public string UserCreated { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<System.DateTime> FreezeToDate { get; set; }
        public string Note { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DateFinished { get; set; }
        public string UserFinished { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual UserSubscription UserSubscription { get; set; }
    }
}
