//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstructorSalary
    {
        public int Id { get; set; }
        public string InstructorId { get; set; }
        public double RateSalary { get; set; }
        public int Classes { get; set; }
        public double AmountSalary { get; set; }
        public System.DateTime DateSalary { get; set; }
        public bool Confirmed { get; set; }
        public System.DateTime DateConfirmed { get; set; }
        public string UserConfirmed { get; set; }
        public string Note { get; set; }
        public double AmountDaily { get; set; }
        public double Adjustment { get; set; }
        public double Total { get; set; }
        public double RateDaily { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
    }
}
