//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstructorDetail
    {
        public int Id { get; set; }
        public string InstructorId { get; set; }
        public string ColorCode { get; set; }
        public double Rate { get; set; }
        public double DailyRate { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
