//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSGType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MSGType()
        {
            this.SysAlerts = new HashSet<SysAlert>();
            this.UserSMSses = new HashSet<UserSMSs>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Message { get; set; }
        public bool Active { get; set; }
        public bool AutoSend { get; set; }
        public Nullable<int> TimeBefore { get; set; }
        public int CompanyId { get; set; }
        public int MessageTypeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysAlert> SysAlerts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserSMSs> UserSMSses { get; set; }
        public virtual Company Company { get; set; }
    }
}
