//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileTracking
    {
        public int Id { get; set; }
        public string UserID { get; set; }
        public System.DateTime Date { get; set; }
        public string Picture { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> BMI { get; set; }
        public Nullable<decimal> Fat { get; set; }
        public Nullable<decimal> Dim_Hands { get; set; }
        public Nullable<decimal> Dim_Legs { get; set; }
        public Nullable<decimal> Dim_Thighs { get; set; }
        public Nullable<decimal> Dim_Waist { get; set; }
        public decimal WeightChange { get; set; }
        public Nullable<decimal> Fat_HandL { get; set; }
        public Nullable<decimal> Fat_HandR { get; set; }
        public Nullable<decimal> Fat_LegR { get; set; }
        public Nullable<decimal> Fat_LegL { get; set; }
        public Nullable<decimal> Fat_Belly { get; set; }
        public Nullable<decimal> Mucsle { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
