//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmsSender
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime SendDate { get; set; }
        public string Sender { get; set; }
        public string Recipients { get; set; }
        public string RefId { get; set; }
        public string Source { get; set; }
        public bool Sent { get; set; }
        public string Message { get; set; }
        public string UserId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
