//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudioPlacement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudioPlacement()
        {
            this.ClassAvailablePlacements = new HashSet<ClassAvailablePlacement>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int StudioId { get; set; }
        public bool IsDeleted { get; set; }
        public int Places { get; set; }
        public int TypeId { get; set; }
    
        public virtual Studio Studio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassAvailablePlacement> ClassAvailablePlacements { get; set; }
    }
}
