//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSubscription
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserSubscription()
        {
            this.ClassEnrollments = new HashSet<ClassEnrollment>();
            this.ClassWaitLists = new HashSet<ClassWaitList>();
            this.FrozenSubscriptions = new HashSet<FrozenSubscription>();
            this.UserBalanceTrackings = new HashSet<UserBalanceTracking>();
        }
    
        public int Id { get; set; }
        public string UserId { get; set; }
        public System.DateTime DateSubscribed { get; set; }
        public int NumClasses { get; set; }
        public Nullable<System.DateTime> DateExpire { get; set; }
        public int CurrentBalance { get; set; }
        public int ClassesDone { get; set; }
        public Nullable<double> AmountPaid { get; set; }
        public string UserCreated { get; set; }
        public bool Active { get; set; }
        public int SubscriptionTypeId { get; set; }
        public bool Frozen { get; set; }
        public Nullable<System.DateTime> DateExpireOriginal { get; set; }
        public bool IsFirst { get; set; }
        public int LateCacelation { get; set; }
        public bool IsLate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassEnrollment> ClassEnrollments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassWaitList> ClassWaitLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FrozenSubscription> FrozenSubscriptions { get; set; }
        public virtual SubscriptionType SubscriptionType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserBalanceTracking> UserBalanceTrackings { get; set; }
    }
}
